const ingredientCategories = {
    "Vihannekset ja juurekset": [
        "bataatti",
        "juuriselleri",
        "kaprikset",
        "kesäkurpitsa",
        "keittojuurekset (pakaste)",
        "kirsikkatomaatit",
        "kukkakaali",
        "kurkku",
        "lanttu",
        "lehtipersilja",
        "miniluumutomaatit",
        "myrskikurpitsa",
        "palsternakka",
        "paprika",
        "parsakaali",
        "peruna",
        "peruna-sipulisekoitus (pakaste)",
        "perunaviipaleet (pakaste)",
        "Pirkka lehtikaalisuikaleet",
        "porkkana",
        "punajuuri",
        "punasipuli",
        "purjo",
        "ruusukaali",
        "salaatti",
        "salaattiherneet",
        "salottisipuli",
        "selleri",
        "sipuli",
        "sipulikeittoainekset",
        "sipulikuutiot",
        "tomaatti",
        "valkokaali",
        "valkosipulinkynsi",
        "vihreitä pitkät pavut",
        "wok-vihannessekoitus (pakaste) tai itämaisia wokvihanneksia (pakaste)",
        "kevätsipuli"
    ],

    "Hedelmät & sitrukset": [
        "lime",
        "limetti",
        "limetinmehu",
        "sitruuna",
        "sitruunalohkoja",
        "sitruunankuori",
        "sitruunanmehu",
        "sitruunalohkoja"
    ],

    "Liha": [
        "broilerin fileesuikaleet",
        "broilerin jauheliha",
        "grillimakkara",
        "kananfondi",
        "kirjolohifilee",
        "kylmäsavulohi",
        "lenkkimakkara",
        "lohifilee",
        "luutonta naudan etuselkää, lapaa tai ulkopaistia",
        "naudan jauheliha",
        "saunapalvikinkku",
        "sian jauheliha",
        "sika-nautajauheliha",
        "siskonmakkara",
        "Snellman Chorizo All Natural -makkara",
        "suomalainen pekoni",
        "uunimakkara"
    ],

    "Kasviproteiinit": [
        "kylmäsavutofu",
        "luomu tofu",
        "maustamaton kiinteä tofu",
        "maustamatonta kiinteää tofua",
        "soijavalmiste",
        "vegefileesuikaleet"
    ],

    "Pavut, siemenet & pähkinät": [
        "herneet",
        "kidneypavut suolaliemessä",
        "kikherneet suolaliemessä",
        "kuoritut maapähkinät paahdettuna",
        "mantelilastut",
        "pekāanipähkinät",
        "pinjansiemenet",
        "valkoiset pavut"
    ],

    "Maitotuotteet & kasvipohjaiset": [
        "chavre levite",
        "crème fraîche",
        "emmental-mozzarellajuustoraaste",
        "emmentaljuustoraaste",
        "fetajuusto",
        "juusto",
        "kaura kasvirasvasekoite",
        "kerma",
        "kevytmaito",
        "kokosmaito",
        "laktoositon ruokakerma",
        "maito",
        "maustamaton kauragurtti",
        "maustettu ruokakerma (cheddar ja paahdettu sipuli)",
        "pippurikerma",
        "ruokakerma",
        "täysmaito",
        "turkkilainen jogurtti",
        "tuorejuusto",
        "vuohenjuusto",
        "maustamaton tuorejuusto"
    ],

    "Viljatuotteet, pasta & nuudelit": [
        "fusillipasta",
        "kierremakaroni",
        "makaroni",
        "munanuudelit",
        "nuudelit",
        "pasta",
        "pitkäjyväinen riisi",
        "riisi",
        "riisinuudelit",
        "spagetti",
        "piirakkapohja",
        "piirakkataikina",
        "tortillachipsit"
    ],

    "Mausteet & yrtit": [
        "basilika",
        "basilikan lehdet",
        "cayennepippuri",
        "chilirouhe",
        "inkivääri",
        "juustokumina",
        "kaneli",
        "keltainen currytahna",
        "korianteri",
        "kurkuma",
        "laakerinlehti",
        "meirami",
        "mustapippuri",
        "oregano",
        "pizzamauste",
        "punainen chili",
        "savupaprikajauhe",
        "tacomausteseos",
        "tilli",
        "timjami",
        "tuore timjami",
        "yrttitomaattimurska"
    ],

    "Öljyt & rasvat": [
        "ekstra-neitsytoliiviöljy",
        "oliiviöljy",
        "paahdettu seesamiöljy",
        "paahdettua seesamiöljyä",
        "rypsiöljy",
        "voi",
        "öljy",
        "margariini",
        "kaura kasvirasvasekoite"
    ],

    "Säilykkeet & kastikkeet": [
        "aurinkokuivatut tomaatit",
        "balsamiviinietikka",
        "chilitomaattisose",
        "curry-tahna",
        "Dijon-sinappi",
        "hoisinkastike",
        "hunaja",
        "juustokumina",
        "kalaliemi",
        "kana- tai lihafondi",
        "kasvisfondi",
        "kasvisliemikuutio",
        "kidneypavut",
        "limetinmehu",
        "makea chilikastike",
        "maapähkinävoi",
        "pesto",
        "rapea valkosipuli",
        "salsadippi (vahva)",
        "soijakastike",
        "tomaattimurska",
        "tomaattisose",
        "kastike",
        "punainen pesto",
        "vaahterasiirappia",

        "maustekurkku",
        "rapea valkosipulia",
        "kiinalainen soijakastike"
    ],

    "Kuiva-aineet": [
        "korppujauhot",
        "punaiset linssit",
        "vehnäjauhot",
        "sokeri",
        "suola"
    ],

    "Muut": [
        "vesi",
        "kananmuna",
    ]
};
